version: '3'
services:
  commentary-service:
    build:
      context: ./commentary-service
      dockerfile: dockerfile
    ports:
      - 8082:8082

  event-service:
    build:
      context: ./event-service
      dockerfile: dockerfile
    ports:
      - 8083:8083
    
  post-service:
    build:
      context: ./post-service
      dockerfile: dockerfile
    ports:
      - 8081:8081
    
  query-service:
    build:
      context: ./query-service
      dockerfile: dockerfile
    ports:
      - 8084:8084

  verify-comment-service:
    build:
      context: ./verify-comment-service
      dockerfile: dockerfile
    ports:
      - 8085:8085



