apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: microservice-blog
build:
  artifacts:
    - image: adamjurcz/commentary-service
      context: commentary-service
      docker:
        dockerfile: dockerfile
    - image: adamjurcz/event-service
      context: event-service
      docker:
        dockerfile: dockerfile
    - image: adamjurcz/post-service
      context: post-service
      docker:
        dockerfile: dockerfile
    - image: adamjurcz/query-service
      context: query-service
      docker:
        dockerfile: dockerfile
    - image: adamjurcz/verify-comment-service
      context: verify-comment-service
      docker:
        dockerfile: dockerfile
    - image: adamjurcz/frontend
      context: ../microservice-blog-frontend
      docker:
        dockerfile: dockerfile
manifests:
  rawYaml:
    - manifest/init/mongodb-query-pv.yml
    - manifest/init/mongodb-query-pvc.yml
    - manifest/init/mongodb-query-deployment.yml
    - manifest/init/postgres-post-pv.yml
    - manifest/init/postgres-post-pvc.yml
    - manifest/init/postgres-post-deployment.yml
    - manifest/event-deployment.yml
    - manifest/commentary-deployment.yml
    - manifest/post-deployment.yml
    - manifest/query-deployment.yml
    - manifest/verify-comment-deployment.yml
    - manifest/frontend-deployment.yml
    - manifest/frontend-ingress.yml
