apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-query-pv
  labels:
    name: mongodb-query-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/mongodb"

