apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-post-pv
  labels:
    name: postgres-post-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: "/mnt/data/postgres"

