apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-post-deployment
spec:
  selector:
    matchLabels:
      app: postgres-post
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-post
    spec:
      containers:
        - name: postgres-post
          image: postgres:10.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db0
            - name: POSTGRES_USER
              value: root_user
            - name: POSTGRES_PASSWORD
              value: password123
          volumeMounts:
            - name: postgres-post-persistent-storage
              mountPath: "/var/lib/postgresql/data"
      volumes:
        - name: postgres-post-persistent-storage
          persistentVolumeClaim:
            claimName: postgres-post-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-post-service
spec:
  selector:
    app: postgres-post
  ports:
    - name: postgres
      port: 5432
