apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-post-pvc
  labels:
    app: postgres-post
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: postgres-post-pv
