apiVersion: apps/v1
kind: Deployment
metadata:
  name: commentary-deployment
  labels:
    app: commentary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commentary
  template:
    metadata:
      labels:
        app: commentary
    spec:
      initContainers:
      - name: wait-for-kafka
        image: busybox:1.28
        command: ['sh', '-c', 'until nslookup kafka-service; do echo waiting for kafka; sleep 2; done;']
      containers:
      - name: commentary-pod
        image: adamjurcz/commentary-service:latest
        ports:
        - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: commentary-service
spec:
  selector:
    app: commentary
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
