apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-query-pvc
  labels:
    app: mongodb-query
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: mongodb-query-pv
